my_blog/blog/urls.py
from django.urls import path, re_path, include
from django.views.static import serve
from . import views
from django.conf import settings

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('sign_up/', views.sign_up, name='sign_up'),
    path('new/', views.new_article, name='new_article'),
    path('@<str:username>/<int:article_id>/', views.show_article, name='article'),
    path('@<str:username>/', views.show_publication, name='publication'),
    path('<int:pk>/edit/', views.edit_article, name='edit_article'),
    path('api/', include('blog.API_urls')),
    path('tags/<str:tag_name>/', views.show_tag, name='tags'),
    path('topics/<str:topic_name>/', views.show_topic, name='topics'),
]


if settings.DEBUG:
    urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]

my_blog/my_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts.views import profile_view


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/profile/', profile_view, name='profile'),
    path('', include('blog.urls')),

]

my_blog/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.core.validators import MinLengthValidator
from django.contrib.postgres.fields import ArrayField
from django.contrib.auth.models import Group
import pymongo
import numpy
import redis


class Article(models.Model):
	is_vectorized = models.BooleanField(default=False)
	is_active = models.BooleanField('نمایش عمومی؟', default=True)
	is_valid = models.BooleanField('تایید شده؟', default=False)
	pub_date = models.DateTimeField('زمان انتشار', auto_now_add=True)
	val_date = models.DateTimeField('زمان تایید', null=True, blank=True)
	img_path = models.ImageField('محل ذخیره تصویر', upload_to='%Y/%m/%d/', max_length=750)
	title = models.CharField('عنوان مقاله', max_length=350)
	text = models.TextField('متن مقاله', validators=[MinLengthValidator(300)])
	author = models.ForeignKey(
		'BlogUser', on_delete=models.CASCADE, related_name='published', verbose_name='نویسنده')
	validator = models.ForeignKey('BlogUser', on_delete=models.PROTECT, null=True,
		blank=True, related_name='Avalidated', verbose_name='تایید کننده')
	tag = models.ManyToManyField('Tag', blank=True, verbose_name='برچسب')
	topic = models.ForeignKey(
		'Topic', on_delete=models.PROTECT, verbose_name='دسته بندی')
	user_liked = models.ManyToManyField(
		'BlogUser', through='ArticleLike', related_name='alikes', verbose_name='پسند')


	def save(self, *args, **kwargs):
		if self.is_valid and self.val_date is None:
			self.val_date = timezone.now()
		elif not self.is_valid and self.val_date is not None:
			self.val_date = None
		super().save(*args, **kwargs)

	class Meta:
		ordering = ['-pub_date']

	def get_likes(self):
		return self.user_liked.through.objects.filter(is_like=True, article=self).count()

	def get_dislikes(self):
		return self.user_liked.through.objects.filter(is_like=False, article=self).count()

	def user_like_status(self, user):
		try:
			obj = ArticleLike.objects.get(user=user, article=self)
			if obj.is_like == True:
				return {'did_like': True, 
						'is_like': True, 
						'like_count': self.get_likes(), 
						'dislike_count': self.get_dislikes()}
			else:
				return {'did_like': True, 
						'is_like': False, 
						'like_count': self.get_likes(), 
						'dislike_count': self.get_dislikes()}
		except ArticleLike.DoesNotExist:
			return {'did_like': False, 
					'is_like': False, 
					'like_count': self.get_likes(), 
					'dislike_count': self.get_dislikes()}


	def __str__(self):
		return self.title


class Comment(models.Model):
	text = models.CharField('متن نظر', max_length=200)
	is_valid = models.BooleanField('تایید شده؟', default=False)
	pub_date = models.DateTimeField('زمان انتشار', auto_now_add=True)
	val_date = models.DateTimeField('زمان تایید', null=True, blank=True)
	user = models.ForeignKey('BlogUser', on_delete=models.CASCADE,
	related_name='comments', verbose_name='نویسنده')
	validator = models.ForeignKey('BlogUser', on_delete=models.PROTECT, null=True,
		blank=True, related_name='Cvalidated', verbose_name='تایید کننده')
	article = models.ForeignKey(
		'Article', on_delete=models.CASCADE, verbose_name='مقاله')
	response_to = models.ForeignKey('self', on_delete=models.CASCADE, null=True,
		blank=True, related_name='response', verbose_name='پاسخ به')
	user_liked = models.ManyToManyField(
		'BlogUser', through='CommentLike', related_name='clikes', verbose_name='پسند')

	def save(self, *args, **kwargs):
		if self.is_valid and self.val_date is None:
			self.val_date = timezone.now()
		elif not self.is_valid and self.val_date is not None:
			self.val_date = None
		super().save(*args, **kwargs)

	def get_likes(self):
		return self.user_liked.through.objects.filter(is_like=True, comment=self).count()

	def get_dislikes(self):
		return self.user_liked.through.objects.filter(is_like=False, comment=self).count()

	def get_responses(self):
		return self.response.all().values_list('text')

	def __str__(self):
		return self.text

	def user_like_status(self, user):
		try:
			obj = CommentLike.objects.get(user=user, comment=self)
			if obj.is_like == True:
				return {'did_like': True, 
						'is_like': True, 
						'like_count': self.get_likes(), 
						'dislike_count': self.get_dislikes()}
			else:
				return {'did_like': True, 
						'is_like': False, 
						'like_count': self.get_likes(), 
						'dislike_count': self.get_dislikes()}
		except CommentLike.DoesNotExist:
			return {'did_like': False, 
					'is_like': False, 
					'like_count': self.get_likes(), 
					'dislike_count': self.get_dislikes()}


class BlogUser(User):

	def user_directory_path(self, filename):
		return f'user/user_{self.id}/{filename}'

	phone_number = models.CharField('شماره تلفن', max_length=11)
	img_path = models.ImageField('محل ذخیره عکس', upload_to=user_directory_path)
	is_author = models.BooleanField('نویسنده است؟', default=False)
	is_editor = models.BooleanField('ویراستار است؟', default=False)
	is_manager = models.BooleanField('مدیر است؟', default=False)
	is_inactive = models.BooleanField('غیر فعال شده؟', default=False)
	followers = models.ManyToManyField(
		'self', symmetrical=False, through='Follow', related_name='followedBy', verbose_name='دنبال کردن')
	bookmarked_articles = models.ManyToManyField(
		'Article', through='Bookmark', related_name='bookmarkedBy', verbose_name='نشان کردن')
	bio = models.CharField('درباره من', max_length=250)

	def save(self, *args, **kwargs):
		if self.is_manager:
			self.groups.add(Group.objects.get(name='managers'))

		super().save(*args, **kwargs)

	def __str__(self):
		return self.username

	def full_name(self):
		return self.first_name + ' ' + self.last_name

	def user_follow_status(self, user):
		try:
			obj = Follow.objects.get(author=self, user=user)
			return {'follow': True, 'followers': self.followedBy.count()}
		except Follow.DoesNotExist:
			return {'follow': False, 'followers': self.followedBy.count()}


class Tag(models.Model):
	name = models.CharField('برچسب', max_length=55, unique=True)

	def __str__(self):
		return self.name


class Topic(models.Model):
	name = models.CharField('دسته بندی', max_length=55)
	super_topic = models.ForeignKey(
		'self', on_delete=models.SET_NULL, null=True, blank=True, related_name='subtopics', verbose_name='فرا مجموعه')

	def __str__(self):
		return self.name


class ArticleLike(models.Model):
	article = models.ForeignKey(
		'Article', on_delete=models.CASCADE, verbose_name='مقاله')
	user = models.ForeignKey(
		'BlogUser', on_delete=models.CASCADE, verbose_name='کاربر')
	is_like = models.BooleanField('پسند؟', default=True)

	class Meta:
		constraints = [
			models.UniqueConstraint(
			fields=['article', 'user'], name='article_like')
		]

	def __str__(self):
		return self.user.username + '، ' + self.article.title + ("پسندید." if self.is_like else 'نپسندید.')


class CommentLike(models.Model):
	comment = models.ForeignKey(
		'Comment', on_delete=models.CASCADE, verbose_name='نظر')
	user = models.ForeignKey(
		'BlogUser', on_delete=models.CASCADE, verbose_name='کاربر')
	is_like = models.BooleanField('پسند؟', default=True)

	class Meta:
		constraints = [
			models.UniqueConstraint(
			fields=['comment', 'user'], name='comment_like')
		]


	def __str__(self):
		return self.user.username + '، ' + self.comment.text + ("پسندید." if self.is_like else 'نپسندید.')


class Follow(models.Model):
	author = models.ForeignKey(
		'BlogUser', on_delete=models.CASCADE, related_name='follower', verbose_name='نویسنده')
	user = models.ForeignKey('BlogUser', on_delete=models.CASCADE,
	related_name='following', verbose_name='کاربر')

	class Meta:
		constraints = [
		models.UniqueConstraint(fields=['author', 'user'], name='follow')
		]

	def __str__(self):
		return self.user.username + '، ' + self.author.username + "را دنبال کرد."


class Bookmark(models.Model):
	article = models.ForeignKey(
		'Article', on_delete=models.CASCADE, related_name='bookmarkers', verbose_name='مقاله')
	user = models.ForeignKey('BlogUser', on_delete=models.CASCADE,
		related_name='bookmarks', verbose_name='کاربر')

	class Meta:
		constraints = [
			models.UniqueConstraint(
			fields=['article', 'user'], name='bookmark')
		]

	def __str__(self):
		return self.user.username + '، ' + self.article.title + "را نشان کرد."


class ArticleVector(models.Model):
	article = models.OneToOneField(
		Article,
		on_delete=models.CASCADE,
		primary_key=True,
	)

	embedding = ArrayField(
		models.FloatField(),
		size=100
	)
	
	@classmethod
	def get_embedding_matrice(clf):
		return numpy.array(clf.objects.values_list('embedding', flat=True))

	@classmethod
	def get_articl_ids(clf):
		return numpy.array(clf.objects.values_list('article', flat=True))

myclient = pymongo.MongoClient()
mydb = myclient["word2vec"]
#R = redis.Redis(decode_responses=True)


class WordVector:
	def __init__(self):
		self.collection = mydb["words"]

	def _get_word(self, word):
		return self.collection.find_one({"word": word})

	def _get_unknown_by_length(self, word):
		word_length = len(word)
		vec_list = self.collection.distinct('vector', {'$where': 'this.word.length == {word_length}'})
		return numpy.mean(vec_list, axis=0).tolist()


	def _get_word_vector(self, word):
		dic = self._get_word(word)

		if dic is not None:
			return numpy.array(dic["vector"])

#		if not R.exists(f'unknown_{len(word)}'):
#			R.rpush(f'unknown_{len(word)}', *self._get_unknown_by_length(word))

#		return numpy.array(R.lrange(f'unknown_{len(word)}'), dtype='float32')

	def get_vector(self, query):
		words = query.split()

		return numpy.mean([self._get_word_vector(word) for word in words], axis=0)

my_blog/blog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import ModelForm
from .models import *


class SignUpForm(UserCreationForm):
	class Meta:
		model = BlogUser
		fields = ('username',
				  'first_name',
				  'last_name',
				  'email',
				  'phone_number',
				  'img_path',
				  'bio',
				  )


class ArticleCreationForm(ModelForm):
	class Meta:
		model = Article
		fields = ('title', 
				  'text',
				  'img_path', 
				  'tag', 
				  'topic', 
				  'is_active',)


class CommentForm(ModelForm):
	class Meta:
		model = Comment
		fields = ('text', 'response_to')

my_blog/blog/templates/article_form.html
{% extends 'index.html' %}
{% block title %} مقاله جدید {% endblock %}
{% load bootstrap5 %}
{% load static %} 
{% block content %}

{% if error %} 
<div role="alert"> {{ error }} </div> 
{% endif %}

<div class="col-11">
<form id="new-form" method="post" enctype="multipart/form-data" autocomplete="off"> 
	{% csrf_token %}

	{{ form.title.errors }}

	<div class="new-page1">
		<div class="form-floating mb-3 ">
			<input type="text " name="{{ form.title.name }}" maxlength="150" required id="id_title" class="form-control" value="{{ form.title.data }}" placeholder="">
			
		</div>
		{{ form.text.errors }}
		<div class="form-floating">
			<textarea class="form-control h-100 " name="{{ form.text.name }}" row="1" rows="5" required id="id_text" placeholder="">{% if form.text.data != None %}{{ form.text.data }}{% endif %}</textarea>
			<label class="keep-right" for="id_text">نوشتن رو شروع کن، بذار افکار جریان پیدا کنند</label>
			
		</div>
		<div  class="d-grid gap-2 mt-2">
			<div id="continue" class="btn btn-outline-primary" > ادامه </div>
		</div>
	</div>
	<div class="new-page2" style="display: none;">

		<div class="container py-5">

		
			<div class="row ">
				<div class="col-lg-6 mx-auto">
		
					<!-- Upload image input-->
					<div class="input-group mb-3 px-2 py-2 rounded-pill bg-dark shadow-sm">
					<input name="{{ form.img_path.name }}" required id="upload" type="file"  class="form-control border-0">
						<label id="upload-label" for="upload" class="font-weight-light keep-right text-muted">آپلود تصویر</label>
						<div class="input-group-append">
							<label for="upload" class="btn btn-light m-0 rounded-pill px-4"> 
								<i class="fa fa-cloud-upload text-muted"></i>
								<small class="text-uppercase font-weight-bold text-muted">انتخاب فایل</small>
							</label>
						</div>
					</div>
		
					<!-- Uploaded image area-->
					<div class="image-area mt-4">
						<img id="imageResult" src="#" alt="" class="img-fluid rounded shadow-sm mx-auto d-block">
					</div>
		
				</div>
			</div>
		</div>

<div class="d-flex justify-content-between">
<div class="col-5">
<select class="form-select mb-3" name="topic" required id="id_topic">

  	<option value="" selected>دسته بندی کلی مقاله را مشخص کنید</option>
	{% for option in form.topic|slice:"1:" %}
  	{{ option }}
    {% endfor %}
</select>
</div>
<div class="d-flex flex-column col-5">
<div class="form-check form-switch">
  <input class="form-check-input" type="checkbox" name="is_active" id="id_is_active" checked>
  <label class="form-check-label" for="id_is_active">مقاله آماده انتشار است؟</label>
</div>
<div class="form-check form-switch">
  <input class="form-check-input" type="checkbox" name="is_valid" id="id_is_valid">
  <label class="form-check-label" for="id_is_valid">مقاله جهت تایید ویراستار ارسال شود؟</label>
</div>
</div>
</div>
<div class="d-flex flex-wrap " id="tagbox">
<input class="rounded p-2 bg-transparent" type="text" list="datalistOptions" id="tag-input" placeholder="برچسب مناسب اضافه کنید">
<datalist id="datalistOptions">

</datalist>

</div>


<select class="d-none" name="tag" id="id_tag" multiple>

</select>
	<div class="d-flex justify-content-between mt-2">
		<div id="back" class="btn btn-outline-secondary col-2" > برگشت </div>

		<button class="btn btn-outline-primary col-9" type="submit">ذخیره</button>
	</div>
</div>
</form>
</div>

{% endblock %}
{% block script %}<script src="{% static 'blog/new_article_script.js' %}"></script>{% endblock %}

my_blog/blog/templates/new_article.html
{% extends 'index.html' %}
{% block title %} مقاله جدید {% endblock %}
{% load bootstrap5 %}
{% load static %} 
{% block content %}

{% if error %} 
<div role="alert"> {{ error }} </div> 
{% endif %}

<div class="col-11">
<form id="new-form" method="post" enctype="multipart/form-data" autocomplete="off"> 
	{% csrf_token %}

	{{ form.title.errors }}

	<div class="new-page1">
		<div class="form-floating mb-3 ">
			<input type="text " name="{{ form.title.name }}" maxlength="150" required id="id_title" class="form-control" value="{% if form.title.data != None %}{{ form.title.data }}{% endif %}" placeholder="">
			<label class="keep-right" for="id_title">عنوان کوتاه نوشته ات رو جذاب می کنه</label>
			
		</div>
		{{ form.text.errors }}
		<div class="form-floating">
			<textarea class="form-control h-100 " name="{{ form.text.name }}" row="1" rows="5" required id="id_text" placeholder="">{% if form.text.data != None %}{{ form.text.data }}{% endif %}</textarea>
			<label class="keep-right" for="id_text">نوشتن رو شروع کن، بذار افکار جریان پیدا کنند</label>
			
		</div>
		<div  class="d-grid gap-2 mt-2">
			<div id="continue" class="btn btn-outline-primary" > ادامه </div>
		</div>
	</div>
	<div class="new-page2" style="display: none;">

		<div class="container py-5">

		
			<div class="row ">
				<div class="col-lg-6 mx-auto">
		
					<!-- Upload image input-->
					<div class="input-group mb-3 px-2 py-2 rounded-pill bg-dark shadow-sm">
					<input name="{{ form.img_path.name }}" required id="upload" type="file"  class="form-control border-0">
						<label id="upload-label" for="upload" class="font-weight-light keep-right text-muted">آپلود تصویر</label>
						<div class="input-group-append">
							<label for="upload" class="btn btn-light m-0 rounded-pill px-4"> 
								<i class="fa fa-cloud-upload text-muted"></i>
								<small class="text-uppercase font-weight-bold text-muted">انتخاب فایل</small>
							</label>
						</div>
					</div>
		
					<!-- Uploaded image area-->
					<div class="image-area mt-4">
						<img id="imageResult" src="#" alt="" class="img-fluid rounded shadow-sm mx-auto d-block">
					</div>
		
				</div>
			</div>
		</div>

<div class="d-flex justify-content-between">
<div class="col-5">
<select class="form-select mb-3" name="topic" required id="id_topic">

  	<option value="" selected>دسته بندی کلی مقاله را مشخص کنید</option>
	{% for option in form.topic|slice:"1:" %}
  	{{ option }}
    {% endfor %}
</select>
</div>
<div class="d-flex flex-column col-5">
<div class="form-check form-switch">
  <input class="form-check-input" type="checkbox" name="is_active" id="id_is_active" checked>
  <label class="form-check-label" for="id_is_active">مقاله آماده انتشار است؟</label>
</div>
</div>
</div>
<div class="d-flex flex-wrap " id="tagbox">
<input class="rounded p-2 bg-transparent" type="text" list="datalistOptions" id="tag-input" placeholder="برچسب مناسب اضافه کنید">
<datalist id="datalistOptions">

</datalist>

</div>


<select class="d-none" name="tag" id="id_tag" multiple>

</select>
	<div class="d-flex justify-content-between mt-2">
		<div id="back" class="btn btn-outline-secondary col-2" > برگشت </div>

		<button class="btn btn-outline-primary col-9" type="submit">ذخیره</button>
	</div>
</div>
</form>
</div>

{% endblock %}
{% block script %}<script src="{% static 'blog/new_article_script.js' %}"></script>{% endblock %}

my_blog/blog/templates/sign_up.html
{% extends 'index.html' %}
{% block title %} ثبت نام {% endblock %}
{% load bootstrap5 %}
{% block content %}

{% if error %} 
<div role="alert"> {{ error }} </div> 
{% endif %}

<h2>Sign up</h2>
<form method="post" enctype="multipart/form-data"> 
  {% csrf_token %}
  {% bootstrap_form form %} 
  <button type="submit"> ثبت نام </button>
</form>
{% endblock %}